### ISSUE TITLE
pourquoi

### ISSUE THREAD

**Issue by justekoro** [perizuki/overwatch-rap-battle#1]
pourquoi ce repo

**Comment by perizuki** [comment]
wshhhhhhgggggg j’avais oublié ça va mon pote koro

**Comment by justekoro** [comment]
ça va tranquille et toi

**Comment by perizuki** [comment]
oklm

**Comment by justekoro** [comment]
tu deviens quoi ça fait longtemps

**Comment by perizuki** [comment]
bah rien là y’a pas longtemps j’ai sauté stv mon nouveau compte c cpasperi

**Comment by justekoro** [comment]
je vais te follow alors 👍👍👍
